name: 'Salesforce SFDX MarkDown report generator'
author: Anshul Verma (Cynoteck Technology Solutions LLC)
description: 'This action parses SFDX generated logs/reports and generates markdown report ready to be added within actions workflow step summary'
inputs:
  i:
    description: path of log/report file to be parsed
    required: false
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'terminal'
  color: 'purple'
